/*

 PIANOLAYOUTCOLOR.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : C:\Users\A_Rival\Documents\Programming\GB\muddygb_dsd\gfx\pianoroll2.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 193
   Split data    : Yes
   Block size    : 256

 This file was generated by GBMB v1.8

*/

#define PianoLayoutWidth 20
#define PianoLayoutHeight 2
#define PianoLayoutBank 0

#define PianoLayoutBLK0 PianoLayoutBLK0PLN0
extern unsigned char PianoLayoutBLK0PLN0[];
extern unsigned char PianoLayoutBLK0PLN1[];

/* End of PIANOLAYOUTCOLOR.H */
