/*

 PIANOLAYOUT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : C:\Users\A_Rival\Documents\Programming\GB\muddygb_dsd\gfx\pianoroll2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 97
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define PianoLayoutWidth 20
#define PianoLayoutHeight 2
#define PianoLayoutBank 0

extern unsigned char PianoLayout[];

/* End of PIANOLAYOUT.H */
